/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.ng2-menu-item[_ngcontent-%COMP%] {\n    font-family: "Roboto", "Helvetica Neue", Helvetica, Arial;\n\n    padding: 0 1.25rem;\n    background: #fff;\n    color: #444;\n    cursor: pointer;\n    font-size: 15px;\n    text-transform: none;\n    font-weight: 400;\n    transition: background 0.2s;\n    letter-spacing: 0.03em;\n    height: 48px;\n    line-height: 48px;\n\n    text-overflow: ellipsis;\n    white-space: nowrap;\n    overflow-x: hidden;\n}\n\n.ng2-menu-item--selected[_ngcontent-%COMP%] {\n    background: #f9f9f9;\n    outline: 0;\n}\n\n.ng2-menu-item[_ngcontent-%COMP%]:focus {\n    outline: 0;\n}\n\n.ng2-menu-item[_ngcontent-%COMP%]:active {\n    background: #eee;\n}\n\n.ng2-menu-item[_ngcontent-%COMP%]   [ng2-menu-item-icon][_ngcontent-%COMP%] {\n    vertical-align: bottom;\n    font-size: 28px;\n    width: 40px;\n    height: 40px;\n    color: rgba(0, 0, 0, 0.54);\n}'];